import java.util.Scanner;

public class Rgbooleans {
    public static void main (String [] arg){
        Scanner sc = new Scanner(System.in);
        String p = "\uD83C\uDFA8";

        String ANSI_RED = "\u001B[31m";
        String ANSI_GREEN = "\u001B[32m";
        String ANSI_BLUE = "\u001B[34m";
        String ANSI_RED_BACKGROUND = "\u001B[41m";
        String ANSI_GREEN_BACKGROUND = "\u001B[42m";
        String ANSI_BLUE_BACKGROUND = "\u001B[44m";
        String ANSI_RESET = "\u001B[0m";

        System.out.println("╔═══════════════════════════╗");
        System.out.println("║       RGB Booleans        ║");
        System.out.println("║      SINGLE PLAYER     ╔══╩═╗");
        System.out.println("║     by Jouse Márquez   ║ "+p+" ║");
        System.out.println("╚════════════════════════╩════╝");

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES SENCILLOS        ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println(ANSI_RED_BACKGROUND+"¿Vas a usar TODO el bote rojo? (True/False)"+ANSI_RESET);
        boolean rojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND+"¿Vas a usar TODO el bote verde? (True/False)"+ANSI_RESET);
        boolean verde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND+"¿Vas a usar TODO el bote azul? (True/False)"+ANSI_RESET);
        boolean azul = sc.nextBoolean();

        System.out.println("¿Se va a pintar VERDE?"+" "+(!rojo & verde & !azul));
        System.out.println("¿Se va a pintar AZUL?"+" " +(!rojo & !verde & azul));
        System.out.println("¿Se va a pintar NEGRO?"+" " +(!rojo & !verde & !azul));
        System.out.println("¿Se va a pintar AMARILLO?"+" " +(rojo & verde & !azul));
        System.out.println("¿Se va a pintar FUCSIA?"+" " +(rojo & !verde & azul));
        System.out.println("¿Se va a pintar CELESTE?"+" " +(!rojo & verde & azul));
        System.out.println("¿Se va a pintar BLANCO?"+" " +(rojo & verde & azul));

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES COMPUESTOS       ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println("¿Vas a usar TODO el bote rojo? (True/False)");
        rojo = sc.nextBoolean();
        System.out.println("¿Vas a usar TODO el bote verde? (True/False)");
        verde = sc.nextBoolean();
        System.out.println("¿Vas a usar TODO el bote azul? (True/False)");
        azul = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote rojo? (True/False)");
        boolean medioRojo = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote verde? (True/False)");
        boolean medioVerde = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote azul? (True/False)");
        boolean medioAzul = sc.nextBoolean();

        System.out.println("¿Se va a pintar NARANJA?"+" "+(rojo & medioVerde & !azul));
        System.out.println("¿Se va a pintar VERDE LIMA?"+" "+(medioRojo & verde & !azul));
        System.out.println("¿Se va a pintar ROSA?"+" "+(medioRojo & !verde & medioAzul));
        System.out.println("¿Se va a pintar MORADO?"+" "+(medioRojo & !verde & azul));
        System.out.println("¿Se va a pintar VERDE CLARITO?"+" "+(!rojo & verde & medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO?"+" "+(!rojo & medioVerde & azul));
        System.out.println("¿Se va a pintar GRANATE?"+" "+(medioRojo & !verde & !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO?"+" "+(!rojo & medioVerde & !azul));
        System.out.println("¿Se va a pintar AZUL MARINO?"+" "+(!rojo & !verde & !medioAzul));
        System.out.println("¿Se va a pintar ORO?"+" "+(medioRojo & medioVerde & !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO?"+" "+(!rojo & medioVerde & !medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO?"+" "+(medioRojo & !verde & !medioAzul));
        System.out.println("¿Se va a pintar GRIS?"+" "+(medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar COLOR 1?"+" "+(medioRojo & medioVerde & azul));
        System.out.println("¿Se va a pintar COLOR 2?"+" "+(medioRojo & verde & medioAzul));
        System.out.println("¿Se va a pintar COLOR 3?"+" "+(medioRojo & verde & azul));
        System.out.println("¿Se va a pintar COLOR 4?"+" "+(rojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar COLOR 5?"+" "+(rojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar COLOR 6?"+" "+(rojo & verde & medioAzul));

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES MÚLTIPLES        ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println("¿Vas a usar TODO el bote rojo? (True/False)");
        rojo = sc.nextBoolean();
        System.out.println("¿Vas a usar TODO el bote verde? (True/False)");
        verde = sc.nextBoolean();
        System.out.println("¿Vas a usar TODO el bote azul? (True/False)");
        azul = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote rojo? (True/False)");
        medioRojo = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote verde? (True/False)");
        medioVerde = sc.nextBoolean();
        System.out.println("¿Vas a usar MEDIO bote azul? (True/False)");
        medioAzul = sc.nextBoolean();

        System.out.println("¿Se va a pintar Verde o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        /*SOLO PRIMER VALOR*/
        System.out.println("¿Se va a pintar Verde o Negro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Amarillo?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Fucsia?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Celeste?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Blanco?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Naranja?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Verde Lima?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Rosa?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Morado?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Verde Clarito?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Azul Claro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Granate?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Verde oscuro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Azul Marino?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Oro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Celeste Oscuro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Morado Oscuro?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o Gris?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));

        /*ME QUEDÉ AQUÍ*/
        System.out.println("¿Se va a pintar Verde o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde o ( 127, 127 , 255 )?"+" "+(!rojo & verde & !azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Negro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Amarillo o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Fucsia o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Blanco o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Naranja o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Lima o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Rosa o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde Clarito o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Claro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Granate o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Verde oscuro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Azul Marino o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Oro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Celeste Oscuro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Morado Oscuro o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar Gris o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 127 , 255 ) o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 127 , 255 ) o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 127 , 255 ) o ( 255 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 127 , 255 ) o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o Gris?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o ( 127 , 255 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o ( 127 , 255 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o ( 255 , 127 , 127 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o ( 255 , 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 255 , 255 , 127 ) o ( 127, 127 , 255 )?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Verde?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Azul?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Negro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Amarillo?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Fucsia?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Celeste?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Blanco?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Naranja?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Verde Lima?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Rosa?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Morado?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Verde Clarito?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Azul Claro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Granate?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Verde oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Azul Marino?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Oro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Celeste Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));
        System.out.println("¿Se va a pintar ( 127, 127 , 255 ) o Morado Oscuro?"+" "+(!rojo & verde & azul || !medioRojo & medioVerde & medioAzul));

        /*

        */
    }
}
