import java.util.Scanner;

public class Rgbooleans {
    public static void main(String[] arg) {

        /* Para la realización de este ejercicio se ha comprobado los códigos de color RGB en la siguiente página web:
         * https://www.color-blindness.com/color-name-hue/ realizando correcciones en el ejercicio.*/

        Scanner sc = new Scanner(System.in);
        String p = "\uD83C\uDFA8";

        String ANSI_RED = "\u001B[31m";
        String ANSI_GREEN = "\u001B[32m";
        String ANSI_BLUE = "\u001B[34m";
        String ANSI_RED_BACKGROUND = "\u001B[41m";
        String ANSI_GREEN_BACKGROUND = "\u001B[42m";
        String ANSI_BLUE_BACKGROUND = "\u001B[44m";
        String ANSI_RESET = "\u001B[0m";

        System.out.println("╔═══════════════════════════╗");
        System.out.println("║       RGB Booleans        ║");
        System.out.println("║      SINGLE PLAYER     ╔══╩═╗");
        System.out.println("║     by Jouse Márquez   ║ " + p + " ║");
        System.out.println("╚════════════════════════╩════╝");

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES SENCILLOS        ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println(ANSI_RED_BACKGROUND + "¿Vas a usar TODO el bote rojo? (True/False)" + ANSI_RESET);
        boolean rojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND + "¿Vas a usar TODO el bote verde? (True/False)" + ANSI_RESET);
        boolean verde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND + "¿Vas a usar TODO el bote azul? (True/False)" + ANSI_RESET);
        boolean azul = sc.nextBoolean();

        System.out.println("¿Se va a pintar VERDE?" + " " + (!rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL?" + " " + (!rojo && !verde && azul));
        System.out.println("¿Se va a pintar NEGRO?" + " " + (!rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AMARILLO?" + " " + (rojo && verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA?" + " " + (rojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE?" + " " + (!rojo && verde && azul));
        System.out.println("¿Se va a pintar BLANCO?" + " " + (rojo && verde && azul));

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES COMPUESTOS       ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println(ANSI_RED_BACKGROUND + "¿Vas a usar TODO el bote rojo? (True/False)" + ANSI_RESET);
        rojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND + "¿Vas a usar TODO el bote verde? (True/False)" + ANSI_RESET);
        verde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND + "¿Vas a usar TODO el bote azul? (True/False)" + ANSI_RESET);
        azul = sc.nextBoolean();
        System.out.println(ANSI_RED_BACKGROUND + "¿Vas a usar MEDIO bote rojo? (True/False)" + ANSI_RESET);
        boolean medioRojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND + "¿Vas a usar MEDIO bote verde? (True/False)" + ANSI_RESET);
        boolean medioVerde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND + "¿Vas a usar MEDIO bote azul? (True/False)" + ANSI_RESET);
        boolean medioAzul = sc.nextBoolean();

        System.out.println("¿Se va a pintar NARANJA?" + " " + (rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA?" + " " + (medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar ROSA?" + " " + (medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO?" + " " + (medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO?" + " " + (!rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO?" + " " + (!rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRANATE?" + " " + (medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO?" + " " + (!rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO?" + " " + (!rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar ORO?" + " " + (medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO?" + " " + (!rojo && medioVerde && !medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO?" + " " + (medioRojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar GRIS?" + " " + (medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO?" + " " + (medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA?" + " " + (medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO?" + " " + (medioRojo && verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA?" + " " + (rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA?" + " " + (rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER?" + " " + (rojo && verde && medioAzul));

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║        COLORES MÚLTIPLES        ║");
        System.out.println("╚═════════════════════════════════╝");

        System.out.println(ANSI_RED_BACKGROUND + "¿Vas a usar TODO el bote rojo? (True/False)" + ANSI_RESET);
        rojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND + "¿Vas a usar TODO el bote verde? (True/False)" + ANSI_RESET);
        verde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND + "¿Vas a usar TODO el bote azul? (True/False)" + ANSI_RESET);
        azul = sc.nextBoolean();
        System.out.println(ANSI_RED_BACKGROUND + "¿Vas a usar MEDIO bote rojo? (True/False)" + ANSI_RESET);
        medioRojo = sc.nextBoolean();
        System.out.println(ANSI_GREEN_BACKGROUND + "¿Vas a usar MEDIO bote verde? (True/False)" + ANSI_RESET);
        medioVerde = sc.nextBoolean();
        System.out.println(ANSI_BLUE_BACKGROUND + "¿Vas a usar MEDIO bote azul? (True/False)" + ANSI_RESET);
        medioAzul = sc.nextBoolean();

        System.out.println("¿Se va a pintar VERDE o AZUL?" + " " + (!rojo && verde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE o NEGRO?" + " " + (!rojo && verde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE o AMARILLO?" + " " + (!rojo && verde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE o MAGENTA?" + " " + (!rojo && verde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE o CELESTE?" + " " + (!rojo && verde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE o BLANCO?" + " " + (!rojo && verde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE o NARANJA?" + " " + (!rojo && verde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE o VERDE LIMA?" + " " + (!rojo && verde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE o ROSA?" + " " + (!rojo && verde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o MORADO?" + " " + (!rojo && verde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE o VERDE CLARITO?" + " " + (!rojo && verde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o AZUL CLARO?" + " " + (!rojo && verde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE o GRANATE?" + " " + (!rojo && verde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE o VERDE OSCURO?" + " " + (!rojo && verde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE o AZUL MARINO?" + " " + (!rojo && verde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar VERDE u ORO?" + " " + (!rojo && verde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE o CELESTE OSCURO?" + " " + (!rojo && verde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o MORADO OSCURO?" + " " + (!rojo && verde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o GRIS?" + " " + (!rojo && verde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o VERDE MENTA?" + " " + (!rojo && verde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o AZUL ELÉCTRICO?" + " " + (!rojo && verde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE o MANDARINA VIVA?" + " " + (!rojo && verde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o FUCSIA?" + " " + (!rojo && verde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE o LIMÓN LÁSER?" + " " + (!rojo && verde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE o AZUL PIZARRA CLARO?" + " " + (!rojo && verde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL o VERDE?" + " " + (!rojo && !verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL o NEGRO?" + " " + (!rojo && !verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL o AMARILLO?" + " " + (!rojo && !verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL o MAGENTA?" + " " + (!rojo && !verde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL o CELESTE?" + " " + (!rojo && !verde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL o BLANCO?" + " " + (!rojo && !verde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL o NARANJA?" + " " + (!rojo && !verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL o VERDE LIMA?" + " " + (!rojo && !verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL o ROSA?" + " " + (!rojo && !verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o MORADO?" + " " + (!rojo && !verde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL o VERDE CLARITO?" + " " + (!rojo && !verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o AZUL CLARO?" + " " + (!rojo && !verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL o GRANATE?" + " " + (!rojo && !verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL o VERDE OSCURO?" + " " + (!rojo && !verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL o AZUL MARINO?" + " " + (!rojo && !verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar AZUL u ORO?" + " " + (!rojo && !verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL o CELESTE OSCURO?" + " " + (!rojo && !verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o MORADO OSCURO?" + " " + (!rojo && !verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o GRIS?" + " " + (!rojo && !verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o VERDE MENTA?" + " " + (!rojo && !verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o AZUL ELÉCTRICO?" + " " + (!rojo && !verde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL o MANDARINA VIVA?" + " " + (!rojo && !verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o FUCSIA?" + " " + (!rojo && !verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL o LIMÓN LÁSER?" + " " + (!rojo && !verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL o AZUL PIZARRA CLARO?" + " " + (!rojo && !verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NEGRO o VERDE?" + " " + (!rojo && !verde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar NEGRO o AZUL?" + " " + (!rojo && !verde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar NEGRO o AMARILLO?" + " " + (!rojo && !verde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar NEGRO o MAGENTA?" + " " + (!rojo && !verde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar NEGRO o CELESTE?" + " " + (!rojo && !verde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar NEGRO o BLANCO?" + " " + (!rojo && !verde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar NEGRO o NARANJA?" + " " + (!rojo && !verde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar NEGRO o VERDE LIMA?" + " " + (!rojo && !verde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar NEGRO o ROSA?" + " " + (!rojo && !verde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o MORADO?" + " " + (!rojo && !verde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar NEGRO o VERDE CLARITO?" + " " + (!rojo && !verde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o AZUL CLARO?" + " " + (!rojo && !verde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NEGRO o GRANATE?" + " " + (!rojo && !verde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar NEGRO o VERDE OSCURO?" + " " + (!rojo && !verde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar NEGRO o AZUL MARINO?" + " " + (!rojo && !verde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar NEGRO u ORO?" + " " + (!rojo && !verde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar NEGRO o CELESTE OSCURO?" + " " + (!rojo && !verde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o MORADO OSCURO?" + " " + (!rojo && !verde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o GRIS?" + " " + (!rojo && !verde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o VERDE MENTA?" + " " + (!rojo && !verde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o AZUL ELÉCTRICO?" + " " + (!rojo && !verde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar NEGRO o MANDARINA VIVA?" + " " + (!rojo && !verde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o FUCSIA?" + " " + (!rojo && !verde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NEGRO o LIMÓN LÁSER?" + " " + (!rojo && !verde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NEGRO o AZUL PIZARRA CLARO?" + " " + (!rojo && !verde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AMARILLO o VERDE?" + " " + (rojo && verde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o AZUL?" + " " + (rojo && verde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o NEGRO?" + " " + (rojo && verde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o MAGENTA?" + " " + (rojo && verde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o CELESTE?" + " " + (rojo && verde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o BLANCO?" + " " + (rojo && verde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o NARANJA?" + " " + (rojo && verde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o VERDE LIMA?" + " " + (rojo && verde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o ROSA?" + " " + (rojo && verde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o MORADO?" + " " + (rojo && verde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o VERDE CLARITO?" + " " + (rojo && verde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o AZUL CLARO?" + " " + (rojo && verde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AMARILLO o GRANATE?" + " " + (rojo && verde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o VERDE OSCURO?" + " " + (rojo && verde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o AZUL MARINO?" + " " + (rojo && verde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar AMARILLO u ORO?" + " " + (rojo && verde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AMARILLO o CELESTE OSCURO?" + " " + (rojo && verde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o MORADO OSCURO?" + " " + (rojo && verde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o GRIS?" + " " + (rojo && verde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o VERDE MENTA?" + " " + (rojo && verde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o AZUL ELÉCTRICO?" + " " + (rojo && verde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar AMARILLO o MANDARINA VIVA?" + " " + (rojo && verde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o FUCSIA?" + " " + (rojo && verde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AMARILLO o LIMÓN LÁSER?" + " " + (rojo && verde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AMARILLO o AZUL PIZARRA CLARO?" + " " + (rojo && verde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MAGENTA o VERDE?" + " " + (rojo && !verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o AZUL?" + " " + (rojo && !verde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar MAGENTA o NEGRO?" + " " + (rojo && !verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o AMARILLO?" + " " + (rojo && !verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o CELESTE?" + " " + (rojo && !verde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar MAGENTA o BLANCO?" + " " + (rojo && !verde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar MAGENTA o NARANJA?" + " " + (rojo && !verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o VERDE LIMA?" + " " + (rojo && !verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o ROSA?" + " " + (rojo && !verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o MORADO?" + " " + (rojo && !verde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar MAGENTA o VERDE CLARITO?" + " " + (rojo && !verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o AZUL CLARO?" + " " + (rojo && !verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MAGENTA o GRANATE?" + " " + (rojo && !verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o VERDE OSCURO?" + " " + (rojo && !verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o AZUL MARINO?" + " " + (rojo && !verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar MAGENTA u ORO?" + " " + (rojo && !verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MAGENTA o CELESTE OSCURO?" + " " + (rojo && !verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o MORADO OSCURO?" + " " + (rojo && !verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o GRIS?" + " " + (rojo && !verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o VERDE MENTA?" + " " + (rojo && !verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o AZUL ELÉCTRICO?" + " " + (rojo && !verde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar MAGENTA o MANDARINA VIVA?" + " " + (rojo && !verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o FUCSIA?" + " " + (rojo && !verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MAGENTA o LIMÓN LÁSER?" + " " + (rojo && !verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MAGENTA o AZUL PIZARRA CLARO?" + " " + (rojo && !verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE o VERDE?" + " " + (!rojo && verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE o AZUL?" + " " + (!rojo && verde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE o NEGRO?" + " " + (!rojo && verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar CELESTE o AMARILLO?" + " " + (!rojo && verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE o MAGENTA?" + " " + (!rojo && verde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE o BLANCO?" + " " + (!rojo && verde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar CELESTE o NARANJA?" + " " + (!rojo && verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE o VERDE LIMA?" + " " + (!rojo && verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE o ROSA?" + " " + (!rojo && verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o MORADO?" + " " + (!rojo && verde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE o VERDE CLARITO?" + " " + (!rojo && verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o AZUL CLARO?" + " " + (!rojo && verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE o GRANATE?" + " " + (!rojo && verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar CELESTE o VERDE OSCURO?" + " " + (!rojo && verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE o AZUL MARINO?" + " " + (!rojo && verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar CELESTE u ORO?" + " " + (!rojo && verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE o CELESTE OSCURO?" + " " + (!rojo && verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o MORADO OSCURO?" + " " + (!rojo && verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o GRIS?" + " " + (!rojo && verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o VERDE MENTA?" + " " + (!rojo && verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o AZUL ELÉCTRICO?" + " " + (!rojo && verde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar CELESTE o MANDARINA VIVA?" + " " + (!rojo && verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o FUCSIA?" + " " + (!rojo && verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE o LIMÓN LÁSER?" + " " + (!rojo && verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE o AZUL PIZARRA CLARO?" + " " + (!rojo && verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar BLANCO o VERDE?" + " " + (rojo && verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar BLANCO o AZUL?" + " " + (rojo && verde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar BLANCO o NEGRO?" + " " + (rojo && verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar BLANCO o AMARILLO?" + " " + (rojo && verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar BLANCO o MAGENTA?" + " " + (rojo && verde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar BLANCO o CELESTE?" + " " + (rojo && verde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar BLANCO o NARANJA?" + " " + (rojo && verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar BLANCO o VERDE LIMA?" + " " + (rojo && verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar BLANCO o ROSA?" + " " + (rojo && verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o MORADO?" + " " + (rojo && verde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar BLANCO o VERDE CLARITO?" + " " + (rojo && verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o AZUL CLARO?" + " " + (rojo && verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar BLANCO o GRANATE?" + " " + (rojo && verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar BLANCO o VERDE OSCURO?" + " " + (rojo && verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar BLANCO o AZUL MARINO?" + " " + (rojo && verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar BLANCO u ORO?" + " " + (rojo && verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar BLANCO o CELESTE OSCURO?" + " " + (rojo && verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o MORADO OSCURO?" + " " + (rojo && verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o GRIS?" + " " + (rojo && verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o VERDE MENTA?" + " " + (rojo && verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o AZUL ELÉCTRICO?" + " " + (rojo && verde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar BLANCO o MANDARINA VIVA?" + " " + (rojo && verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o FUCSIA?" + " " + (rojo && verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar BLANCO o LIMÓN LÁSER?" + " " + (rojo && verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar BLANCO o AZUL PIZARRA CLARO?" + " " + (rojo && verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NARANJA o VERDE?" + " " + (rojo && medioVerde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar NARANJA o AZUL?" + " " + (rojo && medioVerde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar NARANJA o NEGRO?" + " " + (rojo && medioVerde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar NARANJA o AMARILLO?" + " " + (rojo && medioVerde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar NARANJA o MAGENTA?" + " " + (rojo && medioVerde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar NARANJA o CELESTE?" + " " + (rojo && medioVerde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar NARANJA o BLANCO?" + " " + (rojo && medioVerde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar NARANJA o VERDE LIMA?" + " " + (rojo && medioVerde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar NARANJA o ROSA?" + " " + (rojo && medioVerde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o MORADO?" + " " + (rojo && medioVerde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar NARANJA o VERDE CLARITO?" + " " + (rojo && medioVerde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o AZUL CLARO?" + " " + (rojo && medioVerde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NARANJA o GRANATE?" + " " + (rojo && medioVerde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar NARANJA o VERDE OSCURO?" + " " + (rojo && medioVerde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar NARANJA o AZUL MARINO?" + " " + (rojo && medioVerde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar NARANJA u ORO?" + " " + (rojo && medioVerde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar NARANJA o CELESTE OSCURO?" + " " + (rojo && medioVerde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o MORADO OSCURO?" + " " + (rojo && medioVerde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o GRIS?" + " " + (rojo && medioVerde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o VERDE MENTA?" + " " + (rojo && medioVerde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o AZUL ELÉCTRICO?" + " " + (rojo && medioVerde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar NARANJA o MANDARINA VIVA?" + " " + (rojo && medioVerde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o FUCSIA?" + " " + (rojo && medioVerde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar NARANJA o LIMÓN LÁSER?" + " " + (rojo && medioVerde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar NARANJA o AZUL PIZARRA CLARO?" + " " + (rojo && medioVerde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o VERDE?" + " " + (medioRojo && verde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o AZUL?" + " " + (medioRojo && verde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o NEGRO?" + " " + (medioRojo && verde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o AMARILLO?" + " " + (medioRojo && verde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o MAGENTA?" + " " + (medioRojo && verde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o CELESTE?" + " " + (medioRojo && verde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o BLANCO?" + " " + (medioRojo && verde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o NARANJA?" + " " + (medioRojo && verde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o ROSA?" + " " + (medioRojo && verde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o MORADO?" + " " + (medioRojo && verde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o VERDE CLARITO?" + " " + (medioRojo && verde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o AZUL CLARO?" + " " + (medioRojo && verde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o GRANATE?" + " " + (medioRojo && verde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o VERDE OSCURO?" + " " + (medioRojo && verde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o AZUL MARINO?" + " " + (medioRojo && verde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA u ORO?" + " " + (medioRojo && verde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE LIMA o CELESTE OSCURO?" + " " + (medioRojo && verde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o MORADO OSCURO?" + " " + (medioRojo && verde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o GRIS?" + " " + (medioRojo && verde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o VERDE MENTA?" + " " + (medioRojo && verde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o AZUL ELÉCTRICO?" + " " + (medioRojo && verde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o MANDARINA VIVA?" + " " + (medioRojo && verde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o FUCSIA?" + " " + (medioRojo && verde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE LIMA o LIMÓN LÁSER?" + " " + (medioRojo && verde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE LIMA o AZUL PIZARRA CLARO?" + " " + (medioRojo && verde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ROSA o VERDE?" + " " + (rojo && !verde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar ROSA o AZUL?" + " " + (rojo && !verde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar ROSA o NEGRO?" + " " + (rojo && !verde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar ROSA o AMARILLO?" + " " + (rojo && !verde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar ROSA o MAGENTA?" + " " + (rojo && !verde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar ROSA o CELESTE?" + " " + (rojo && !verde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar ROSA o BLANCO?" + " " + (rojo && !verde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar ROSA o NARANJA?" + " " + (rojo && !verde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar ROSA o VERDE LIMA?" + " " + (rojo && !verde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar ROSA o MORADO?" + " " + (rojo && !verde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar ROSA o VERDE CLARITO?" + " " + (rojo && !verde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o AZUL CLARO?" + " " + (rojo && !verde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ROSA o GRANATE?" + " " + (rojo && !verde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar ROSA o VERDE OSCURO?" + " " + (rojo && !verde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar ROSA o AZUL MARINO?" + " " + (rojo && !verde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar ROSA u ORO?" + " " + (rojo && !verde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar ROSA o CELESTE OSCURO?" + " " + (rojo && !verde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o MORADO OSCURO?" + " " + (rojo && !verde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o GRIS?" + " " + (rojo && !verde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o VERDE MENTA?" + " " + (rojo && !verde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o AZUL ELÉCTRICO?" + " " + (rojo && !verde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar ROSA o MANDARINA VIVA?" + " " + (rojo && !verde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o FUCSIA?" + " " + (rojo && !verde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ROSA o LIMÓN LÁSER?" + " " + (rojo && !verde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ROSA o AZUL PIZARRA CLARO?" + " " + (rojo && !verde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO o VERDE?" + " " + (medioRojo && !verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO o AZUL?" + " " + (medioRojo && !verde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar MORADO o NEGRO?" + " " + (medioRojo && !verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar MORADO o AMARILLO?" + " " + (medioRojo && !verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO o MAGENTA?" + " " + (medioRojo && !verde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar MORADO o CELESTE?" + " " + (medioRojo && !verde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO o BLANCO?" + " " + (medioRojo && !verde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO o NARANJA?" + " " + (medioRojo && !verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO o VERDE LIMA?" + " " + (medioRojo && !verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO o ROSA?" + " " + (medioRojo && !verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o VERDE CLARITO?" + " " + (medioRojo && !verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o AZUL CLARO?" + " " + (medioRojo && !verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO o GRANATE?" + " " + (medioRojo && !verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar MORADO o VERDE OSCURO?" + " " + (medioRojo && !verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO o AZUL MARINO?" + " " + (medioRojo && !verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar MORADO u ORO?" + " " + (medioRojo && !verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO o CELESTE OSCURO?" + " " + (medioRojo && !verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o MORADO OSCURO?" + " " + (medioRojo && !verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o GRIS?" + " " + (medioRojo && !verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o VERDE MENTA?" + " " + (medioRojo && !verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o AZUL ELÉCTRICO?" + " " + (medioRojo && !verde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO o MANDARINA VIVA?" + " " + (medioRojo && !verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o FUCSIA?" + " " + (medioRojo && !verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO o LIMÓN LÁSER?" + " " + (medioRojo && !verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO o AZUL PIZARRA CLARO?" + " " + (medioRojo && !verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o VERDE?" + " " + (!rojo && verde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AZUL?" + " " + (!rojo && verde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o NEGRO?" + " " + (!rojo && verde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AMARILLO?" + " " + (!rojo && verde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o MAGENTA?" + " " + (!rojo && verde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o CELESTE?" + " " + (!rojo && verde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o BLANCO?" + " " + (!rojo && verde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o NARANJA?" + " " + (!rojo && verde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o VERDE LIMA?" + " " + (!rojo && verde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o ROSA?" + " " + (!rojo && verde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o MORADO?" + " " + (!rojo && verde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AZUL CLARO?" + " " + (!rojo && verde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o GRANATE?" + " " + (!rojo && verde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o VERDE OSCURO?" + " " + (!rojo && verde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AZUL MARINO?" + " " + (!rojo && verde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO u ORO?" + " " + (!rojo && verde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o CELESTE OSCURO?" + " " + (!rojo && verde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o MORADO OSCURO?" + " " + (!rojo && verde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o GRIS?" + " " + (!rojo && verde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o VERDE MENTA?" + " " + (!rojo && verde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AZUL ELÉCTRICO?" + " " + (!rojo && verde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o MANDARINA VIVA?" + " " + (!rojo && verde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o FUCSIA?" + " " + (!rojo && verde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE CLARITO o LIMÓN LÁSER?" + " " + (!rojo && verde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE CLARITO o AZUL PIZARRA CLARO?" + " " + (!rojo && verde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o VERDE?" + " " + (!rojo && medioVerde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o AZUL?" + " " + (!rojo && medioVerde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o NEGRO?" + " " + (!rojo && medioVerde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o AMARILLO?" + " " + (!rojo && medioVerde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o MAGENTA?" + " " + (!rojo && medioVerde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o CELESTE?" + " " + (!rojo && medioVerde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o BLANCO?" + " " + (!rojo && medioVerde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o NARANJA?" + " " + (!rojo && medioVerde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o VERDE LIMA?" + " " + (!rojo && medioVerde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o ROSA?" + " " + (!rojo && medioVerde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o MORADO?" + " " + (!rojo && medioVerde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o VERDE CLARITO?" + " " + (!rojo && medioVerde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o GRANATE?" + " " + (!rojo && medioVerde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o VERDE OSCURO?" + " " + (!rojo && medioVerde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o AZUL MARINO?" + " " + (!rojo && medioVerde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO u ORO?" + " " + (!rojo && medioVerde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL CLARO o CELESTE OSCURO?" + " " + (!rojo && medioVerde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o MORADO OSCURO?" + " " + (!rojo && medioVerde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o GRIS?" + " " + (!rojo && medioVerde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o VERDE MENTA?" + " " + (!rojo && medioVerde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o AZUL ELÉCTRICO?" + " " + (!rojo && medioVerde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o MANDARINA VIVA?" + " " + (!rojo && medioVerde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o FUCSIA?" + " " + (!rojo && medioVerde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL CLARO o LIMÓN LÁSER?" + " " + (!rojo && medioVerde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL CLARO o AZUL PIZARRA CLARO?" + " " + (!rojo && medioVerde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRANATE o VERDE?" + " " + (medioRojo && !verde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar GRANATE o AZUL?" + " " + (medioRojo && !verde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar GRANATE o NEGRO?" + " " + (medioRojo && !verde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar GRANATE o AMARILLO?" + " " + (medioRojo && !verde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar GRANATE o MAGENTA?" + " " + (medioRojo && !verde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar GRANATE o CELESTE?" + " " + (medioRojo && !verde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar GRANATE o BLANCO?" + " " + (medioRojo && !verde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar GRANATE o NARANJA?" + " " + (medioRojo && !verde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRANATE o VERDE LIMA?" + " " + (medioRojo && !verde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar GRANATE o ROSA?" + " " + (medioRojo && !verde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o MORADO?" + " " + (medioRojo && !verde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar GRANATE o VERDE CLARITO?" + " " + (medioRojo && !verde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o AZUL CLARO?" + " " + (medioRojo && !verde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRANATE o VERDE OSCURO?" + " " + (medioRojo && !verde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRANATE o AZUL MARINO?" + " " + (medioRojo && !verde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar GRANATE u ORO?" + " " + (medioRojo && !verde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRANATE o CELESTE OSCURO?" + " " + (medioRojo && !verde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o MORADO OSCURO?" + " " + (medioRojo && !verde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o GRIS?" + " " + (medioRojo && !verde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o VERDE MENTA?" + " " + (medioRojo && !verde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o AZUL ELÉCTRICO?" + " " + (medioRojo && !verde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar GRANATE o MANDARINA VIVA?" + " " + (medioRojo && !verde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o FUCSIA?" + " " + (medioRojo && !verde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRANATE o LIMÓN LÁSER?" + " " + (medioRojo && !verde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRANATE o AZUL PIZARRA CLARO?" + " " + (medioRojo && !verde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o VERDE?" + " " + (!rojo && medioVerde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AZUL?" + " " + (!rojo && medioVerde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o NEGRO?" + " " + (!rojo && medioVerde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AMARILLO?" + " " + (!rojo && medioVerde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o MAGENTA?" + " " + (!rojo && medioVerde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o CELESTE?" + " " + (!rojo && medioVerde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o BLANCO?" + " " + (!rojo && medioVerde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o NARANJA?" + " " + (!rojo && medioVerde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o VERDE LIMA?" + " " + (!rojo && medioVerde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o ROSA?" + " " + (!rojo && medioVerde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o MORADO?" + " " + (!rojo && medioVerde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o VERDE CLARITO?" + " " + (!rojo && medioVerde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AZUL CLARO?" + " " + (!rojo && medioVerde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o GRANATE?" + " " + (!rojo && medioVerde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AZUL MARINO?" + " " + (!rojo && medioVerde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO u ORO?" + " " + (!rojo && medioVerde && !azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o CELESTE OSCURO?" + " " + (!rojo && medioVerde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o MORADO OSCURO?" + " " + (!rojo && medioVerde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o GRIS?" + " " + (!rojo && medioVerde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o VERDE MENTA?" + " " + (!rojo && medioVerde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AZUL ELÉCTRICO?" + " " + (!rojo && medioVerde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o MANDARINA VIVA?" + " " + (!rojo && medioVerde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o FUCSIA?" + " " + (!rojo && medioVerde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE OSCURO o LIMÓN LÁSER?" + " " + (!rojo && medioVerde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE OSCURO o AZUL PIZARRA CLARO?" + " " + (!rojo && medioVerde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o VERDE?" + " " + (!rojo && !verde && !medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o AZUL?" + " " + (!rojo && !verde && !medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o NEGRO?" + " " + (!rojo && !verde && !medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o AMARILLO?" + " " + (!rojo && !verde && !medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o MAGENTA?" + " " + (!rojo && !verde && !medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o CELESTE?" + " " + (!rojo && !verde && !medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o BLANCO?" + " " + (!rojo && !verde && !medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o NARANJA?" + " " + (!rojo && !verde && !medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o VERDE LIMA?" + " " + (!rojo && !verde && !medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o ROSA?" + " " + (!rojo && !verde && !medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o MORADO?" + " " + (!rojo && !verde && !medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o VERDE CLARITO?" + " " + (!rojo && !verde && !medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o AZUL CLARO?" + " " + (!rojo && !verde && !medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o GRANATE?" + " " + (!rojo && !verde && !medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o VERDE OSCURO?" + " " + (!rojo && !verde && !medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO u ORO?" + " " + (!rojo && !verde && !medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL MARINO o CELESTE OSCURO?" + " " + (!rojo && !verde && !medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o MORADO OSCURO?" + " " + (!rojo && !verde && !medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o GRIS?" + " " + (!rojo && !verde && !medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o VERDE MENTA?" + " " + (!rojo && !verde && !medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o AZUL ELÉCTRICO?" + " " + (!rojo && !verde && !medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o MANDARINA VIVA?" + " " + (!rojo && !verde && !medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o FUCSIA?" + " " + (!rojo && !verde && !medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL MARINO o LIMÓN LÁSER?" + " " + (!rojo && !verde && !medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL MARINO o AZUL PIZARRA CLARO?" + " " + (!rojo && !verde && !medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ORO o VERDE?" + " " + (medioRojo && medioVerde && !azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar ORO o AZUL?" + " " + (medioRojo && medioVerde && !azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar ORO o NEGRO?" + " " + (medioRojo && medioVerde && !azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar ORO o AMARILLO?" + " " + (medioRojo && medioVerde && !azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar ORO o MAGENTA?" + " " + (medioRojo && medioVerde && !azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar ORO o CELESTE?" + " " + (medioRojo && medioVerde && !azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar ORO o BLANCO?" + " " + (medioRojo && medioVerde && !azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar ORO o NARANJA?" + " " + (medioRojo && medioVerde && !azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar ORO o VERDE LIMA?" + " " + (medioRojo && medioVerde && !azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar ORO o ROSA?" + " " + (medioRojo && medioVerde && !azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar ORO o MORADO?" + " " + (medioRojo && medioVerde && !azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar ORO o VERDE CLARITO?" + " " + (medioRojo && medioVerde && !azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ORO o AZUL CLARO?" + " " + (medioRojo && medioVerde && !azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ORO o GRANATE?" + " " + (medioRojo && medioVerde && !azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar ORO o VERDE OSCURO?" + " " + (medioRojo && medioVerde && !azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar ORO o AZUL MARINO?" + " " + (medioRojo && medioVerde && !azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar ORO o CELESTE OSCURO?" + " " + (medioRojo && medioVerde && !azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ORO o MORADO OSCURO?" + " " + (medioRojo && medioVerde && !azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar ORO o GRIS?" + " " + (medioRojo && medioVerde && !azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ORO o VERDE MENTA?" + " " + (medioRojo && medioVerde && !azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ORO o AZUL ELÉCTRICO?" + " " + (medioRojo && medioVerde && !azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar ORO o MANDARINA VIVA?" + " " + (medioRojo && medioVerde && !azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar ORO o FUCSIA?" + " " + (medioRojo && medioVerde && !azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar ORO o LIMÓN LÁSER?" + " " + (medioRojo && medioVerde && !azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar ORO o AZUL PIZARRA CLARO?" + " " + (medioRojo && medioVerde && !azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o VERDE?" + " " + (!rojo && medioVerde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AZUL?" + " " + (!rojo && medioVerde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o NEGRO?" + " " + (!rojo && medioVerde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AMARILLO?" + " " + (!rojo && medioVerde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o MAGENTA?" + " " + (!rojo && medioVerde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o CELESTE?" + " " + (!rojo && medioVerde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o BLANCO?" + " " + (!rojo && medioVerde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o NARANJA?" + " " + (!rojo && medioVerde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o VERDE LIMA?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o ROSA?" + " " + (!rojo && medioVerde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o MORADO?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o VERDE CLARITO?" + " " + (!rojo && medioVerde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AZUL CLARO?" + " " + (!rojo && medioVerde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o GRANATE?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o VERDE OSCURO?" + " " + (!rojo && medioVerde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AZUL MARINO?" + " " + (!rojo && medioVerde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO u ORO?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o MORADO OSCURO?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o GRIS?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o VERDE MENTA?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AZUL ELÉCTRICO?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o MANDARINA VIVA?" + " " + (!rojo && medioVerde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o FUCSIA?" + " " + (!rojo && medioVerde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o LIMÓN LÁSER?" + " " + (!rojo && medioVerde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar CELESTE OSCURO o AZUL PIZARRA CLARO?" + " " + (!rojo && medioVerde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o VERDE?" + " " + (medioRojo && !verde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AZUL?" + " " + (medioRojo && !verde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o NEGRO?" + " " + (medioRojo && !verde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AMARILLO?" + " " + (medioRojo && !verde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o MAGENTA?" + " " + (medioRojo && !verde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o CELESTE?" + " " + (medioRojo && !verde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o BLANCO?" + " " + (medioRojo && !verde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o NARANJA?" + " " + (medioRojo && !verde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o VERDE LIMA?" + " " + (medioRojo && !verde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o ROSA?" + " " + (medioRojo && !verde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o MORADO?" + " " + (medioRojo && !verde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o VERDE CLARITO?" + " " + (medioRojo && !verde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AZUL CLARO?" + " " + (medioRojo && !verde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o GRANATE?" + " " + (medioRojo && !verde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o VERDE OSCURO?" + " " + (medioRojo && !verde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AZUL MARINO?" + " " + (medioRojo && !verde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO u ORO?" + " " + (medioRojo && !verde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o CELESTE OSCURO?" + " " + (medioRojo && !verde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o GRIS?" + " " + (medioRojo && !verde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o VERDE MENTA?" + " " + (medioRojo && !verde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AZUL ELÉCTRICO?" + " " + (medioRojo && !verde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o MANDARINA VIVA?" + " " + (medioRojo && !verde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o FUCSIA?" + " " + (medioRojo && !verde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MORADO OSCURO o LIMÓN LÁSER?" + " " + (medioRojo && !verde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MORADO OSCURO o AZUL PIZARRA CLARO?" + " " + (medioRojo && !verde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRIS o VERDE?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar GRIS o AZUL?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar GRIS o NEGRO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar GRIS o AMARILLO?" + " " + (medioRojo && medioVerde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar GRIS o MAGENTA?" + " " + (medioRojo && medioVerde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar GRIS o CELESTE?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar GRIS o BLANCO?" + " " + (medioRojo && medioVerde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar GRIS o NARANJA?" + " " + (medioRojo && medioVerde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRIS o VERDE LIMA?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar GRIS o ROSA?" + " " + (medioRojo && medioVerde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o MORADO?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar GRIS o VERDE CLARITO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o AZUL CLARO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRIS o GRANATE?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar GRIS o VERDE OSCURO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRIS o AZUL MARINO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar GRIS u ORO?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar GRIS o CELESTE OSCURO?" + " " + (medioRojo && medioVerde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o MORADO OSCURO?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o VERDE MENTA?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o AZUL ELÉCTRICO?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar GRIS o MANDARINA VIVA?" + " " + (medioRojo && medioVerde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o FUCSIA?" + " " + (medioRojo && medioVerde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar GRIS o LIMÓN LÁSER?" + " " + (medioRojo && medioVerde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar GRIS o AZUL PIZARRA CLARO?" + " " + (medioRojo && medioVerde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o VERDE?" + " " + (medioRojo && verde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o AZUL?" + " " + (medioRojo && verde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o NEGRO?" + " " + (medioRojo && verde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o AMARILLO?" + " " + (medioRojo && verde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o MAGENTA?" + " " + (medioRojo && verde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o CELESTE?" + " " + (medioRojo && verde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o BLANCO?" + " " + (medioRojo && verde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o NARANJA?" + " " + (medioRojo && verde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o VERDE LIMA?" + " " + (medioRojo && verde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o ROSA?" + " " + (medioRojo && verde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o MORADO?" + " " + (medioRojo && verde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o VERDE CLARITO?" + " " + (medioRojo && verde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o AZUL CLARO?" + " " + (medioRojo && verde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o GRANATE?" + " " + (medioRojo && verde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o VERDE OSCURO?" + " " + (medioRojo && verde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o AZUL MARINO?" + " " + (medioRojo && verde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA u ORO?" + " " + (medioRojo && verde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar VERDE MENTA o CELESTE OSCURO?" + " " + (medioRojo && verde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o MORADO OSCURO?" + " " + (medioRojo && verde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o GRIS?" + " " + (medioRojo && verde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o AZUL ELÉCTRICO?" + " " + (medioRojo && verde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o MANDARINA VIVA?" + " " + (medioRojo && verde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o FUCSIA?" + " " + (medioRojo && verde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar VERDE MENTA o LIMÓN LÁSER?" + " " + (medioRojo && verde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar VERDE MENTA o AZUL PIZARRA CLARO?" + " " + (medioRojo && verde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o VERDE?" + " " + (medioRojo && verde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o AZUL?" + " " + (medioRojo && verde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o NEGRO?" + " " + (medioRojo && verde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o AMARILLO?" + " " + (medioRojo && verde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o MAGENTA?" + " " + (medioRojo && verde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o CELESTE?" + " " + (medioRojo && verde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o BLANCO?" + " " + (medioRojo && verde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o NARANJA?" + " " + (medioRojo && verde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o VERDE LIMA?" + " " + (medioRojo && verde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o ROSA?" + " " + (medioRojo && verde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o MORADO?" + " " + (medioRojo && verde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o VERDE CLARITO?" + " " + (medioRojo && verde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o AZUL CLARO?" + " " + (medioRojo && verde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o GRANATE?" + " " + (medioRojo && verde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o VERDE OSCURO?" + " " + (medioRojo && verde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o AZUL MARINO?" + " " + (medioRojo && verde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO u ORO?" + " " + (medioRojo && verde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o CELESTE OSCURO?" + " " + (medioRojo && verde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o MORADO OSCURO?" + " " + (medioRojo && verde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o GRIS?" + " " + (medioRojo && verde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o VERDE MENTA?" + " " + (medioRojo && verde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o MANDARINA VIVA?" + " " + (medioRojo && verde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o FUCSIA?" + " " + (medioRojo && verde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o LIMÓN LÁSER?" + " " + (medioRojo && verde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL ELÉCTRICO o AZUL PIZARRA CLARO?" + " " + (medioRojo && verde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o VERDE?" + " " + (rojo && medioVerde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AZUL?" + " " + (rojo && medioVerde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o NEGRO?" + " " + (rojo && medioVerde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AMARILLO?" + " " + (rojo && medioVerde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o MAGENTA?" + " " + (rojo && medioVerde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o CELESTE?" + " " + (rojo && medioVerde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o BLANCO?" + " " + (rojo && medioVerde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o NARANJA?" + " " + (rojo && medioVerde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o VERDE LIMA?" + " " + (rojo && medioVerde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o ROSA?" + " " + (rojo && medioVerde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o MORADO?" + " " + (rojo && medioVerde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o VERDE CLARITO?" + " " + (rojo && medioVerde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AZUL CLARO?" + " " + (rojo && medioVerde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o GRANATE?" + " " + (rojo && medioVerde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o VERDE OSCURO?" + " " + (rojo && medioVerde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AZUL MARINO?" + " " + (rojo && medioVerde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA u ORO?" + " " + (rojo && medioVerde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o CELESTE OSCURO?" + " " + (rojo && medioVerde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o MORADO OSCURO?" + " " + (rojo && medioVerde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o GRIS?" + " " + (rojo && medioVerde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o VERDE MENTA?" + " " + (rojo && medioVerde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AZUL ELÉCTRICO?" + " " + (rojo && medioVerde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o FUCSIA?" + " " + (rojo && medioVerde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o LIMÓN LÁSER?" + " " + (rojo && medioVerde && medioAzul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar MANDARINA VIVA o AZUL PIZARRA CLARO?" + " " + (rojo && medioVerde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar FUCSIA o VERDE?" + " " + (rojo && medioVerde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o AZUL?" + " " + (rojo && medioVerde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o NEGRO?" + " " + (rojo && medioVerde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o AMARILLO?" + " " + (rojo && medioVerde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o MAGENTA?" + " " + (rojo && medioVerde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o CELESTE?" + " " + (rojo && medioVerde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o BLANCO?" + " " + (rojo && medioVerde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o NARANJA?" + " " + (rojo && medioVerde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o VERDE LIMA?" + " " + (rojo && medioVerde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o ROSA?" + " " + (rojo && medioVerde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o MORADO?" + " " + (rojo && medioVerde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o VERDE CLARITO?" + " " + (rojo && medioVerde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o AZUL CLARO?" + " " + (rojo && medioVerde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar FUCSIA o GRANATE?" + " " + (rojo && medioVerde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o VERDE OSCURO?" + " " + (rojo && medioVerde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o AZUL MARINO?" + " " + (rojo && medioVerde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o ORO?" + " " + (rojo && medioVerde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar FUCSIA o CELESTE OSCURO?" + " " + (rojo && medioVerde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o MORADO OSCURO?" + " " + (rojo && medioVerde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o GRIS?" + " " + (rojo && medioVerde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o VERDE MENTA?" + " " + (rojo && medioVerde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o AZUL ELÉCTRICO?" + " " + (rojo && medioVerde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar FUCSIA o MANDARINA VIVA?" + " " + (rojo && medioVerde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o LIMÓN LÁSER?" + " " + (rojo && medioVerde && azul || rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar FUCSIA o AZUL PIZARRA CLARO?" + " " + (rojo && medioVerde && azul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o VERDE?" + " " + (rojo && verde && medioAzul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AZUL?" + " " + (rojo && verde && medioAzul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o NEGRO?" + " " + (rojo && verde && medioAzul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AMARILLO?" + " " + (rojo && verde && medioAzul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o MAGENTA?" + " " + (rojo && verde && medioAzul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o CELESTE?" + " " + (rojo && verde && medioAzul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o BLANCO?" + " " + (rojo && verde && medioAzul || rojo && verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o NARANJA?" + " " + (rojo && verde && medioAzul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o VERDE LIMA?" + " " + (rojo && verde && medioAzul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o ROSA?" + " " + (rojo && verde && medioAzul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o MORADO?" + " " + (rojo && verde && medioAzul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o VERDE CLARITO?" + " " + (rojo && verde && medioAzul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AZUL CLARO?" + " " + (rojo && verde && medioAzul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o GRANATE?" + " " + (rojo && verde && medioAzul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o VERDE OSCURO?" + " " + (rojo && verde && medioAzul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AZUL MARINO?" + " " + (rojo && verde && medioAzul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER u ORO?" + " " + (rojo && verde && medioAzul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o CELESTE OSCURO?" + " " + (rojo && verde && medioAzul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o MORADO OSCURO?" + " " + (rojo && verde && medioAzul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o GRIS?" + " " + (rojo && verde && medioAzul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o VERDE MENTA?" + " " + (rojo && verde && medioAzul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AZUL ELÉCTRICO?" + " " + (rojo && verde && medioAzul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o MANDARINA VIVA?" + " " + (rojo && verde && medioAzul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o FUCSIA?" + " " + (rojo && verde && medioAzul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar LIMÓN LÁSER o AZUL PIZARRA CLARO?" + " " + (rojo && verde && medioAzul || medioRojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o VERDE?" + " " + (medioRojo && medioVerde && azul || !rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o AZUL?" + " " + (medioRojo && medioVerde && azul || !rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o NEGRO?" + " " + (medioRojo && medioVerde && azul || !rojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o AMARILLO?" + " " + (medioRojo && medioVerde && azul || rojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o MAGENTA?" + " " + (medioRojo && medioVerde && azul || rojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o CELESTE?" + " " + (medioRojo && medioVerde && azul || !rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o BLANCO?" + " " + (medioRojo && medioVerde && azul || rojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o NARANJA?" + " " + (medioRojo && medioVerde && azul || rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o VERDE LIMA?" + " " + (medioRojo && medioVerde && azul || medioRojo && verde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o ROSA?" + " " + (medioRojo && medioVerde && azul || rojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o MORADO?" + " " + (medioRojo && medioVerde && azul || medioRojo && !verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o VERDE CLARITO?" + " " + (medioRojo && medioVerde && azul || !rojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o AZUL CLARO?" + " " + (medioRojo && medioVerde && azul || !rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o GRANATE?" + " " + (medioRojo && medioVerde && azul || medioRojo && !verde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o VERDE OSCURO?" + " " + (medioRojo && medioVerde && azul || !rojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o AZUL MARINO?" + " " + (medioRojo && medioVerde && azul || !rojo && !verde && !medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO u ORO?" + " " + (medioRojo && medioVerde && azul || medioRojo && medioVerde && !azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o CELESTE OSCURO?" + " " + (medioRojo && medioVerde && azul || !rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o MORADO OSCURO?" + " " + (medioRojo && medioVerde && azul || medioRojo && !verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o GRIS?" + " " + (medioRojo && medioVerde && azul || medioRojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o VERDE MENTA?" + " " + (medioRojo && medioVerde && azul || medioRojo && verde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o AZUL ELÉCTRICO?" + " " + (medioRojo && medioVerde && azul || medioRojo && verde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o MANDARINA VIVA?" + " " + (medioRojo && medioVerde && azul || rojo && medioVerde && medioAzul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o FUCSIA?" + " " + (medioRojo && medioVerde && azul || rojo && medioVerde && azul));
        System.out.println("¿Se va a pintar AZUL PIZARRA CLARO o LIMÓN LÁSER?" + " " + (medioRojo && medioVerde && azul || rojo && verde && medioAzul));

        System.out.println("╔═════════════════════════════════╗");
        System.out.println("║         FIN DEL PROGRAMA        ║");
        System.out.println("╚═════════════════════════════════╝");
    }
}
